spring:
  application:
    name: api-gateway
server:
  port: 5555
zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: hello-service
    api-b:
      path: /api-b/**
      service-id: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://xuezhiqiang:123456@localhost:1111/eureka