spring:
  application:
    name: ribbon-consumer
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://xuezhiqiang:123456@localhost:1111/eureka
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true