eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    hostname: peer2
server:
  port: 1112
spring:
  appclition:
    name: eureka-server
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true