eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1112/eureka
  instance:
    hostname: peer1
server:
  port: 1111
spring:
  appclition:
    name: eureka-server
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true